stages:
  - name: Publish And Build
    steps:
      - publishImageConfig:
          dockerfilePath: ./mongodb/Dockerfile
          buildContext: ./mongodb
          tag: ssh-on-web-mongodb-rancher:${CICD_EXECUTION_SEQUENCE}
  - name: Deploy
    steps:
      - applyYamlConfig:
        path: ./k8s-deploy/mongo-deploy.yaml
