stages:
  - name: Build
    steps:
      - publishImageConfig:
          dockerfilePath: ./mongodb/Dockerfile
          buildContext: ./mongodb
          tag: ssh-on-web-mongodb-rancher:${CICD_EXECUTION_SEQUENCE}

  - name: Build SSHONWEB
    steps:
      - publishImageConfig:
          dockerfilePath: ./Dockerfile
          buildContext: .
          tag: ssh-on-web-rancher:${CICD_EXECUTION_SEQUENCE}
  - name: Deploy
    steps:
      - applyYamlConfig:
          path: ./k8s-deploy/mongo-deploy.yaml
      - applyYamlConfig:
          path: ./k8s-deploy/ssh-on-web-deploy.yaml
