version: '3'
services:
  mongodb:
    image: victor2333/mongo:4.1.4-xenial
    volumes:
      - /data/db/mongo:/data/db
    restart: always
  ssh-on-web:
    # image: victor2333/ssh-on-web:latest
    build: ../
    volumes:
      - /data/ssh-on-web/config:/ssh-on-web/config
    depends_on:
      - mongodb
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - NODE_ENV=production
    restart: always
