apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssh-on-web-mongodb
  labels:
    app: ssh-on-web-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssh-on-web-mongodb
  template:
    metadata:
      labels:
        app: ssh-on-web-mongodb
    spec:
      containers:
        - name: ssh-on-web-mongodb
          image: victor2333/mongo:4.1.4-xenial
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: ssh-on-web-mongodb
              mountPath: /data/db
              subPath: ssh-on-web/mongodb
      volumes:
        - name: ssh-on-web-mongodb
          persistentVolumeClaim:
            claimName: pvc01
---
apiVersion: v1
kind: Service
metadata:
  name: ssh-on-web-mongodb
spec:
  type: ClusterIP
  ports:
    - port: 27017
  selector:
    app: ssh-on-web-mongodb
