apiVersion: extensions/v1beta1 #This is for jenkins build, change to app/v1 is recommanded.
kind: Deployment
metadata:
  name: ssh-on-web
  namespace: ssh-on-web
  labels:
    app: ssh-on-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ssh-on-web
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8080"
      labels:
        app: ssh-on-web
    spec:
      imagePullSecrets:
        - name: pipeline-docker-registry
      containers:
        - name: ssh-on-web
          image: victor2333/ssh-on-web-rancher:${env.BUILD_ID}
          env:
            - name: NODE_ENV
              value: production
            - name: MONGODB_URL
              value: mongodb://ssh-on-web-mongodb:27017/toolsdb
            - name: JWT_SECRET
              value: qwe123asd
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ssh-on-web
  namespace: ssh-on-web
spec:
  type: ClusterIP
  ports:
    - port: 8080
  selector:
    app: ssh-on-web
